### ISSUE TITLE
kereső kérdések

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/bulletinmonitor#4]
- szabadszavas vagy előre meghatározott kulcsszavakra lehessen feliratkozni?
- "hasonló" vagy pontos keresésre van szükség.

**Comment by law909** [comment]
Ha szabadszavas, akkor gyakorlatilag minden feliratkozó keresése külön keresés lehet, ami annyi scraper futást jelent. Érdekes kérdés még, hogy "hasonló" vagy pontos keresésre van szükség.

Szerintem ez alapvetően a scraper fejlesztőktől és a felhasználói igényektől függ.

**Comment by pisipite** [comment]
a scraper nem leszedi úgyis az összes szöveget/adatot? az elején igény szempontjából jobb lenne szabadszavas, amiből később akár a tapasztalatok alapján "kategóriákat" is készíthetnénk.
én a pontos keresést mondanám (+ a ragozott alakok).
